version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      maven-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: npm
    directory: /ts
    schedule:
      interval: weekly
    groups:
      npm-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
